web: 
  container_name: nginx
  image: "nginx:latest"
  ports: 
    - "80:80"
  restart: always
  volumes:
    - ./www:/www
    - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php

php: 
 container_name: php
 build: ./php
 volumes:
   - ./www:/www
 links:
   - db

db:
  container_name: mysql
  image: "mysql:5.7"
  ports:
    - "3306:3306"
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: chocolate

phpmyadmin:
  container_name: phpmyadmin
  image: "phpmyadmin/phpmyadmin"
  links:
    - db
  environment:
    PMA_HOST: mysql
    PMA_PORT: 3306
  ports:
    - "8080:80"
  volumes:
    - /sessions
